### ISSUE TITLE
Failure at Update Readme Discord Badge to latest Upstream

### ISSUE THREAD

**Issue by Harleythetech** [CodexLink/discord-rich-presence-activity-badge#16]
Hi! i tried running your discord badge but unfortunately it fails to run due to an error on "Update Readme Discord Badge to latest Upstream" can you help me fix this?

Err code:
`Run CodexLink/discord-activity-badge@v1.0
/usr/bin/docker run --name codexlinkdiscordactivitybadgelatest_f34f43 --label 0[8](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:9)450d --workdir /github/workspace --rm -e INPUT_DISCORD_USER_ID -e INPUT_DISCORD_BOT_TOKEN -e INPUT_BADGE_IDENTIFIER_NAME -e INPUT_COMMIT_MESSAGE -e INPUT_PROFILE_REPOSITORY -e INPUT_URL_TO_REDIRECT_ON_CLICK -e INPUT_WORKFLOW_TOKEN -e INPUT_CUSTOM_ACTIVITY_STRING -e INPUT_GAME_ACTIVITY_STRING -e INPUT_RICH_PRESENCE_STRING -e INPUT_STREAM_ACTIVITY_STRING -e INPUT_SPOTIFY_ACTIVITY_STRING -e INPUT_ONLINE_STATUS_STRING -e INPUT_IDLE_STATUS_STRING -e INPUT_DND_STATUS_STRING -e INPUT_OFFLINE_STATUS_STRING -e INPUT_CUSTOM_ACTIVITY_COLOR -e INPUT_GAME_ACTIVITY_COLOR -e INPUT_RICH_PRESENCE_COLOR -e INPUT_STREAM_ACTIVITY_COLOR -e INPUT_SPOTIFY_ACTIVITY_COLOR -e INPUT_ONLINE_STATUS_COLOR -e INPUT_IDLE_STATUS_COLOR -e INPUT_DND_STATUS_COLOR -e INPUT_OFFLINE_STATUS_COLOR -e INPUT_STATIC_SUBJECT_STRING -e INPUT_PREFERRED_PRESENCE_CONTEXT -e INPUT_TIME_DISPLAY_OUTPUT -e INPUT_TIME_DISPLAY_ELAPSED_OVERRIDE_STRING -e INPUT_TIME_DISPLAY_REMAINING_OVERRIDE_STRING -e INPUT_TIME_DISPLAY_SHORTHAND -e INPUT_PREFERRED_ACTIVITY_TO_DISPLAY -e INPUT_SHIFT_STATUS_ACTIVITY_COLORS -e INPUT_SPOTIFY_INCLUDE_ALBUM_PLAYLIST_NAME -e INPUT_STATUS_CONTEXT_SEPERATOR -e INPUT_IS_DRY_RUN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/Harleythetech/Harleythetech":"/github/workspace" codexlink/discord-activity-badge:latest
[632ms, INFO] at utils.py:142 -> The logger has been loaded with Coverage Level 20. (INFO)
[632ms, INFO] at entrypoint.py:6[9](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:10) -> Running local mode invocation not detected. Skipping checks for '.env'.
[632ms, INFO] at utils.py:430 -> Environment Variables stored in-memory are successfully resolved!
[633ms, INFO] at api.py:61 -> ClientSession for API Requests has been instantiated.
[640ms, INFO] at api.py:64 -> Discord Client Instantiatied with intents=DISCORD_CLIENT_INTENTS=<Intents value=259>
[640ms, INFO] at api.py:68 -> AsyncGithubAPILite is done initializing other elements.
[643ms, INFO] at api.py:202 -> Attempting to Fetch README from Github API <<< Harleythetech/Harleythetech (https://api.github.com/repos/Harleythetech/Harleythetech/readme)
[643ms, INFO] at badge.py:265 -> Other non-important elements loaded, waiting for the Discord Client Task to finish before continuing...
[776ms, INFO] at badge.py:269 -> Discord Client Task is done. Processing the badge...
[866ms, INFO] at api.py:129 -> Github Profile (Harleythetech/Harleythetech) README has been fetched. | Remaining Requests over Rate-Limit (999/[10](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:11)00)
[867ms, INFO] at badge.py:124 -> Converting README to a Readable Format...
[868ms, INFO] at badge.py:88 -> Conversion from Base64 (String) to Readable README Markdown Format is done and is loaded into the memory!
[868ms, INFO] at badge.py:138 -> Attempting to identify the badge inside README...
[869ms, INFO] at badge.py:157 -> Badge with Identifier ((Script) Discord Activity Badge) not found! New badge will append on the top of the contents of README.md. Please arrange/move the badge once changes has been pushed!
[869ms, INFO] at badge.py:166 -> Awaiting for the badge construction task to finish...
Traceback (most recent call last):
  File "/app/entrypoint.py", line 175, in <module>
    entry_instance: AbstractEventLoop = loop_instance.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 690, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/app/entrypoint.py", line [11](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:12)3, in __start__
    data=[self.readme_data.result()[0], badge_updater.result()],
  File "/app/badge.py", line [17](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:18)1, in check_and_update_badge
    constructed_badge: BadgeStructure = self.badge_task.result()
  File "/app/badge.py", line 271, in construct_badge
    presence_ctx: dict[str, Any] = self.user_ctx[
AttributeError: 'DiscordActivityBadge' object has no attribute 'user_ctx'
Task exception was never retrieved
future: <Task finished name='DiscordClient_UserFetching' coro=<Client.start() done, defined at /usr/local/lib/python3.9/site-packages/discord/client.py:649> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f74afed3340>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f74b0b925e0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f74afed42e0>, 385.992934[19](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:20)9)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f74aff71af0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f74afe61d00>, 385.90[23](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:24)[41](https://github.com/Harleythetech/Harleythetech/runs/6705049372?check_suite_focus=true#step:3:42)981)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f74afed3c70>`

thank you!

**Comment by CodexLink** [comment]
Hello! Thank you for taking an interest in this project, I tried to replicate and it seems I know the issue, the instructions provided were not complete 😟  I accidentally left out where you will get the token part (as far as I side read my README).

Basically, when you are in the part of creating the discord app, you need to create a discord bot there, the reason why is that, bots can read your state if they are part of your guild (server), with that, check the following screenshot and I hope you will get the proper token this time (should be longer than or exactly 70 characters I supposed).

![issue_discord](https://user-images.githubusercontent.com/5953927/171626177-e7e72b38-0e2f-4997-93d0-65abb17bf7f1.png)

Kindly replace your `DISCORD_BOT_TOKEN` with the new secret and let me know if it when okay.

Also note that I will be refactoring the whole thing along with complete instructions this time.

**Comment by Harleythetech** [comment]
**Update**
so the mistake was on my side 😆
Unfortunately I have mistaken Application ID with the Bot's ID that's why it failed after changing the `discord_bot_token` it worked!

Thank you for the fast response!

**Comment by CodexLink** [comment]
Sure no problem! I will be closing this issue as it was resolved.
