### ISSUE TITLE
 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by IotaHydrae** [CodexLink/discord-rich-presence-activity-badge#42]
```
[489ms, INFO] at utils.py:142 -> The logger has been loaded with Coverage Level 20. (INFO)
[489ms, INFO] at entrypoint.py:69 -> Running local mode invocation not detected. Skipping checks for '.env'.
[489ms, INFO] at utils.py:430 -> Environment Variables stored in-memory are successfully resolved!
[489ms, INFO] at api.py:61 -> ClientSession for API Requests has been instantiated.
[495ms, INFO] at api.py:64 -> Discord Client Instantiatied with intents=DISCORD_CLIENT_INTENTS=<Intents value=259>
[495ms, INFO] at api.py:68 -> AsyncGithubAPILite is done initializing other elements.
[496ms, INFO] at api.py:202 -> Attempting to Fetch README from Github API <<< IotaHydrae/IotaHydrae (https://api.github.com/repos/embeddedboys/NINJAR-lite/readme)
[497ms, INFO] at badge.py:265 -> Other non-important elements loaded, waiting for the Discord Client Task to finish before continuing...
[629ms, INFO] at api.py:129 -> Github Profile (embeddedboys/NINJAR-lite) README has been fetched. | Remaining Requests over Rate-Limit (978/1000)
[629ms, INFO] at badge.py:124 -> Converting README to a Readable Format...
[629ms, INFO] at badge.py:88 -> Conversion from Base64 (String) to Readable README Markdown Format is done and is loaded into the memory!
[630ms, INFO] at badge.py:138 -> Attempting to identify the badge inside README...
[630ms, INFO] at badge.py:157 -> Badge with Identifier ((Script) Discord Activity Badge) not found! New badge will append on the top of the contents of README.md. Please arrange/move the badge once changes has been pushed!
[630ms, INFO] at badge.py:166 -> Awaiting for the badge construction task to finish...
[2831ms, INFO] at client.py:77 -> Changed / Pushed Rich Presence to display Activity Badge#3890's status.
[2831ms, INFO] at client.py:108 -> Fetching Discord User's info...
[2955ms, INFO] at client.py:117 -> Discord User iotahydrae0 Fetched.
[2955ms, INFO] at client.py:151 -> Fetching mutual guild from the cached instance client...
[2955ms, INFO] at client.py:179 -> User iotahydrae#0 contains 1 activity.
[2955ms, INFO] at client.py:237 -> Step 2 of 2 | Finished fetching discord user's rich presence and other activities.
[2955ms, INFO] at client.py:90 -> Discord Client is finished fetching data and is saved for badge processing.
[2956ms, INFO] at client.py:95 -> Closing Sessions (1 of 2) | discord.Client -> Done.
[2956ms, INFO] at badge.py:269 -> Discord Client Task is done. Processing the badge...
[2956ms, INFO] at badge.py:295 -> Preferred Activity PreferredActivityDisplay.RICH_PRESENCE does not exists. Using other activity such as GAME_ACTIVITY.
[2956ms, INFO] at badge.py:654 -> The Badge URL has been generated. Link: [![(Script) Discord Activity Badge]([https://badgen.net/badge/Playing%20Game/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%2C%2013%20minutes%20elapsed.?color=61d800&labelColor=00cd90&icon=discord)](https://github.com/embeddedboys/NINJAR-lite](https://badgen.net/badge/Playing%20Game/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%2C%2013%20minutes%20elapsed.?color=61d800&labelColor=00cd90&icon=discord](https://github.com/embeddedboys/NINJAR-lite)))
Constructed? >  [![(Script) Discord Activity Badge]([https://badgen.net/badge/Playing%20Game/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%2C%2013%20minutes%20elapsed.?color=61d800&labelColor=00cd90&icon=discord)](https://github.com/embeddedboys/NINJAR-lite](https://badgen.net/badge/Playing%20Game/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%2C%2013%20minutes%20elapsed.?color=61d800&labelColor=00cd90&icon=discord](https://github.com/embeddedboys/NINJAR-lite)))
[2956ms, INFO] at badge.py:95 -> Conversion from README Readable Raw Content to a Base64 (Bytes) is done and is loaded into the variable for committing changes!
[2956ms, INFO] at badge.py:195 -> There are content changes with the recent README. Allowing to reflect changes!
[2956ms, INFO] at entrypoint.py:129 -> Done loading modules and necessary elements for the process.
[2956ms, INFO] at entrypoint.py:158 -> 2 task/s left to finish the runtime process.
[2956ms, INFO] at api.py:202 -> Attempting to Commit Changes of README from Github API >>> IotaHydrae/IotaHydrae (https://api.github.com/repos/embeddedboys/NINJAR-lite/contents/README.md)
[2957ms, INFO] at entrypoint.py:158 -> 3 task/s left to finish the runtime process.
[2957ms, INFO] at entrypoint.py:158 -> 2 task/s left to finish the runtime process.
[3245ms, INFO] at entrypoint.py:137 -> All tasks successfully finished! Closing Client Sessions...
[3245ms, INFO] at entrypoint.py:144 -> Connection Sessions were successfully closed. (Discord Client and Github API)
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<AsyncGithubAPILite.exec_api_actions() done, defined at /app/api.py:72> exception=SyntaxError('invalid syntax', ('<unknown>', 1, 1, '<ClientResponse(https://api.github.com/repos/embeddedboys/NINJAR-lite/contents/README.md) [409 Conflict]>\n'))>
Traceback (most recent call last):
  File "/app/api.py", line 108, in exec_api_actions
    http_request: ClientResponse = await self._request(
  File "/app/api.py", line 257, in _request
    _resp_ctx: dict = literal_eval(str(_resp_raw))
  File "/usr/local/lib/python3.9/ast.py", line 62, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/local/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    <ClientResponse(https://api.github.com/repos/embeddedboys/NINJAR-lite/contents/README.md) [409 Conflict]>
    ^
SyntaxError: invalid syntax
```

**Comment by IotaHydrae** [comment]
resolved： because branch protection rules
